<?php

declare(strict_types=1);

/**
 * Vite Configuration
 *
 * Configure Vite asset bundler integration.
 * Supports both development (HMR) and production (manifest) modes.
 */

return [
    /*
    |--------------------------------------------------------------------------
    | Manifest Path
    |--------------------------------------------------------------------------
    |
    | Path to Vite's manifest.json file.
    | This file is generated by 'npm run build' in production.
    |
    */
    'manifest_path' => dirname(__DIR__) . '/public/build/.vite/manifest.json',

    /*
    |--------------------------------------------------------------------------
    | Development Server URL
    |--------------------------------------------------------------------------
    |
    | URL of the Vite development server.
    | Used when running 'npm run dev'.
    |
    */
    'dev_server_url' => env('VITE_DEV_SERVER_URL', 'http://localhost:5173'),

    /*
    |--------------------------------------------------------------------------
    | Development Server Enabled
    |--------------------------------------------------------------------------
    |
    | Whether to use Vite dev server in development.
    | Set to false to always use production manifest.
    |
    */
    'dev_server_enabled' => env('VITE_DEV_SERVER_ENABLED', true), // Enable dev server for hot reload

    /*
    |--------------------------------------------------------------------------
    | Build Path
    |--------------------------------------------------------------------------
    |
    | Public path prefix for built assets.
    | This should match your Vite build.outDir configuration.
    |
    */
    'build_path' => env('VITE_BUILD_PATH', '/build'),

    /*
    |--------------------------------------------------------------------------
    | Entry Points
    |--------------------------------------------------------------------------
    |
    | Define your Vite entry points here.
    | These are the main JavaScript files that Vite will bundle.
    |
    | Example:
    | 'entrypoints' => [
    |     'resources/js/app.js',
    |     'resources/js/admin.js',
    | ],
    |
    */
    'entrypoints' => [
        'resources/js/app.js',
    ],
];
